#!/usr/bin/env bash
# Bootstrap VideoMaMa runtime on any Rocky/RHEL 9-class machine with a CUDA GPU.
#
# Builds two ephemeral venvs under /tmp (wiped on reboot on most setups) and
# wires them to the shared checkpoints at CHECKPOINTS_DIR. Code lives wherever
# you cloned/rsynced this repo; nothing is written outside REPO_ROOT except
# /tmp/<venv> and optional ~/.cache/huggingface.
#
# Usage:
#   bash scripts/bootstrap_tmp_venv.sh              # both venvs
#   bash scripts/bootstrap_tmp_venv.sh inference    # inference venv only
#   bash scripts/bootstrap_tmp_venv.sh sam3-ui      # UI venv only
#
# After it finishes, source the generated env file:
#   source "$REPO_ROOT/.videomama-env"

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${REPO_ROOT}/.videomama-env"

DEFAULT_CHECKPOINTS="/mnt/production/project/bcn_lib/work/AI/VideoMaMa/checkpoints"
CHECKPOINTS_DIR="${VIDEOMAMA_CHECKPOINTS:-${DEFAULT_CHECKPOINTS}}"

INFER_VENV="${VIDEOMAMA_VENV:-/tmp/videomama-venv}"
UI_VENV="${VIDEOMAMA_UI_VENV:-/tmp/videomama-sam3-ui-venv}"

INFER_TORCH_INDEX_URL="${INFER_TORCH_INDEX_URL:-https://download.pytorch.org/whl/cu124}"
UI_TORCH_INDEX_URL="${UI_TORCH_INDEX_URL:-https://download.pytorch.org/whl/cu128}"
PYTHON_INFER_BIN="${PYTHON_INFER_BIN:-python3.9}"
PYTHON_UI_BIN="${PYTHON_UI_BIN:-python3.12}"

target="${1:-all}"

log() { printf '[videomama-bootstrap] %s\n' "$*"; }

check_python() {
  local bin="$1" label="$2"
  if ! command -v "$bin" >/dev/null 2>&1; then
    echo "Missing interpreter for $label: $bin" >&2
    echo "Install it (e.g. via pyenv / dnf / uv) or override with PYTHON_${label^^}_BIN=..." >&2
    exit 1
  fi
}

build_inference_venv() {
  log "Building inference venv at ${INFER_VENV} (Python: ${PYTHON_INFER_BIN})"
  check_python "${PYTHON_INFER_BIN}" "infer"

  if [[ ! -d "${INFER_VENV}" ]]; then
    "${PYTHON_INFER_BIN}" -m venv "${INFER_VENV}"
  fi
  # shellcheck disable=SC1091
  source "${INFER_VENV}/bin/activate"
  python -m pip install --upgrade pip setuptools wheel
  python -m pip install --index-url "${INFER_TORCH_INDEX_URL}" \
      torch==2.4.0 torchvision==0.19.0 torchaudio==2.4.0
  python -m pip install -r "${REPO_ROOT}/scripts/requirements-inference.txt"
  deactivate
  log "Inference venv ready."
}

build_ui_venv() {
  log "Building SAM 3 UI venv at ${UI_VENV} (Python: ${PYTHON_UI_BIN})"
  check_python "${PYTHON_UI_BIN}" "ui"

  if [[ ! -d "${UI_VENV}" ]]; then
    "${PYTHON_UI_BIN}" -m venv "${UI_VENV}"
  fi
  # shellcheck disable=SC1091
  source "${UI_VENV}/bin/activate"
  python -m pip install --upgrade pip setuptools wheel
  python -m pip install --index-url "${UI_TORCH_INDEX_URL}" \
      torch==2.10.0 torchvision torchaudio
  python -m pip install -r "${REPO_ROOT}/scripts/requirements-sam3-ui.txt"
  deactivate
  log "SAM 3 UI venv ready."
}

write_env_file() {
  log "Writing env file: ${ENV_FILE}"
  cat > "${ENV_FILE}" <<EOF
# Generated by scripts/bootstrap_tmp_venv.sh on $(date -Iseconds)
export VIDEOMAMA_ROOT="${REPO_ROOT}"
export VIDEOMAMA_CHECKPOINTS="${CHECKPOINTS_DIR}"
export VIDEOMAMA_VENV="${INFER_VENV}"
export VIDEOMAMA_UI_VENV="${UI_VENV}"
export VIDEOMAMA_BASE_MODEL_PATH="\${VIDEOMAMA_BASE_MODEL_PATH:-${CHECKPOINTS_DIR}/stable-video-diffusion-img2vid-xt}"
export VIDEOMAMA_UNET_CHECKPOINT_PATH="\${VIDEOMAMA_UNET_CHECKPOINT_PATH:-${CHECKPOINTS_DIR}/VideoMaMa}"
EOF
}

if [[ ! -d "${CHECKPOINTS_DIR}" ]]; then
  log "WARNING: checkpoints dir does not exist yet: ${CHECKPOINTS_DIR}"
  log "         The env file will still be written; populate the directory before running inference."
fi

case "${target}" in
  all)
    build_inference_venv
    build_ui_venv
    ;;
  inference)
    build_inference_venv
    ;;
  sam3-ui)
    build_ui_venv
    ;;
  *)
    echo "Unknown target: ${target} (expected: all | inference | sam3-ui)" >&2
    exit 2
    ;;
esac

write_env_file

cat <<MSG

[videomama-bootstrap] Done.

Activate inference env:
    source "${ENV_FILE}"
    source "\${VIDEOMAMA_VENV}/bin/activate"

Launch SAM 3 production UI:
    bash "${REPO_ROOT}/scripts/run_production_frame_ui.sh"

Checkpoints: ${CHECKPOINTS_DIR}
MSG
